### ISSUE TITLE
Problems with the initial prep steps

### ISSUE THREAD

**Issue by deversmann** [geerlingguy/mac-dev-playbook#136]
Following the README, on a clean Big Sur install, I install Apple's command line tools and then try to install ansible.  I run the PATH command (2.i.) and then the upgrade pip command with fails.... see trace below.  The PATH command seems to point to nonexistent Python paths and not yet installed Homebrew paths but I couldn't fine the right path for Apple's Python3.  Guidance would be appreciated!  Thanks for everything you do!

```
~ % sudo pip3 install --upgrade pip

Password:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/usr/bin/pip3", line 6, in <module>
    from pip._internal import main
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module> 
   from pip._internal.cli.autocompletion import autocomplete
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinderImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/index/__init__.py)
 ~ % 
```

**Comment by patrckb** [comment]
FWIW, I did the `pip3 install --upgrade pip` _without_ the sudo.

I then had the ~/Library/Python/3.8/bin directory to add to my PATH as per the README.
